name: Publish SmartMan Package

on:
  release:
    types: [created]
  workflow_dispatch:  # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
    
    - name: Build package
      run: python -m build
    
    - name: Verify package name
      run: |
        ls dist/ | grep -i "smartman-"
        pip install -e .
        python -c "import smartman; print(f'Publishing smartman version: {smartman.__version__}')"
    
    - name: Publish package to PyPI
      if: startsWith(github.ref, 'refs/tags')  # Only publish to PyPI when the commit is tagged
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
        verbose: true 